events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Settings Service
    upstream settings_service {
        server settings-service:8080;
    }

    # WebFlux Example App
    upstream webflux_app {
        server settings-webflux-app-example:8081;
    }

    server {
        listen 80;

        # Health check for the gateway itself
        location /health {
            access_log off;
            add_header 'Content-Type' 'application/json';
            return 200 '{"status":"UP"}';
        }

        # Route to Settings Service
        location /schemas/ {
            proxy_pass http://settings_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /settings/ {
            proxy_pass http://settings_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /configurations/ {
            proxy_pass http://settings_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Route to WebFlux Example App
        location /hls/ {
            proxy_pass http://webflux_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Default fallback
        location / {
            return 404 '{"error": "Not Found", "message": "The requested resource was not found on the API Gateway"}';
        }
    }
}
