<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.jlmc</groupId>
        <artifactId>settings-platform-apps-examples</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>settings-platform-se-app</artifactId>

    <dependencies>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.16</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.23</version>
            <scope>runtime</scope>
        </dependency>



        <dependency>
            <groupId>io.github.jlmc</groupId>
            <artifactId>settings-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.jlmc</groupId>
            <artifactId>settings-client</artifactId>
        </dependency>


        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>10.5</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Redis Client Lettuce -->
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>6.6.0.RELEASE</version>
        </dependency>

        <!-- Jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.15.2</version>
        </dependency>


        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>3.2.3</version>
            <scope>runtime</scope>
        </dependency>


        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-retry</artifactId>
            <version>2.2.0</version>
            <scope>runtime</scope>
        </dependency>

    </dependencies>
</project>
