spring.application.name=poc-tdk-settings-l1-l2-app-web-flux

server.port=8081

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://me:me@localhost:27017/tdk-healthcare-db?replicaSet=rs-cluster-example&authSource=admin


tdk.configurations-settings.api-base-url=http://localhost:8080

spring.data.redis.host=x-local-domain
spring.data.redis.port=6379
spring.data.redis.password=YOUR_STRONG_PASSWORD
spring.data.redis.database=0
#spring.data.redis.lettuce.pool.enabled=true
#spring.data.redis.lettuce.pool.max-active=8
#spring.data.redis.lettuce.pool.max-idle=8
#spring.data.redis.lettuce.pool.min-idle=0

#     redis:
#      host: x-local-domain
#      port: 6379
#      password: "YOUR_STRONG_PASSWORD"
#      database: 0
#      lettuce:
#        pool:
#          enabled: true
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: 5s
