spring.application.name=poc-tdk-settings-l1-l2-app-web-flux

server.port=8081

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://me:me@localhost:27017/tdk-healthcare-db?replicaSet=rs-cluster-example&authSource=admin


tdk.configurations-settings.api-base-url=http://localhost:8080
