tdk:
  shared-cache:
    type: NOOP


spring:
  application:
    name: settings-service

  # JACKSON configurations
  jackson:
    # default name strategy
    property-naming-strategy: SNAKE_CASE
    # ignore null properties in the serialization, similar to @JsonInclude(JsonInclude.Include.NON_NULL)
    default-property-inclusion: non_null
    deserialization:
      # Throw an exception if a unknown propriety arrives in the request body, the default value is false
      fail-on-unknown-properties: true
      # throw an exception if a property annotated with @JsonIgnore arrives in the request body, the default value is false
      fail-on-ignored-properties: true

  mvc:
    problemdetails:
      enabled: true

  web:
    resources:
      # Necessary to allowing to handle an exception when the request url do not match in any mapped route
      # this only works when we don't have any static resource for example some web site
      add-mappings: false


  #  MongoDB configuration
  mongodb:
    uri: mongodb://me:me@localhost:27017,localhost:27018/tdk-settings-db?replicaSet=rs-cluster-example&authSource=admin
    #uri: mongodb://mongo1:27017,mongo2:27017/yourdb?replicaSet=rs-cluster-example

  data:
    mongodb:
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
    redis:
      host: x-local-domain
      port: 6379
      password: "YOUR_STRONG_PASSWORD"
      database: 0
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5s


# Enable health liveness and readiness
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  #max-http-header-size: 20480
  max-http-request-header-size: 40KB


logging:
  level:
    io.github.jlmc: TRACE
    # Spring Data MongoDB (repository + template)
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    org.springframework.data.mongodb.core.convert: DEBUG

    # MongoDB Java driver (queries, connections, transactions)
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.connection: INFO
    org.mongodb.driver.protocol.cluster: INFO
    org.mongodb.driver.command: DEBUG
    org.mongodb.driver.connection: INFO
    org.mongodb.driver.cluster: INFO

    # redis
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
