<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.jlmc</groupId>
        <artifactId>settings-platform</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>settings-client</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mockito.version>5.21.0</mockito.version>
        <assertj-core.version>3.27.6</assertj-core.version>
        <junit-jupiter.version>6.0.1</junit-jupiter.version>
    </properties>

    <dependencies>
        <dependency>
            <!-- Mandatory: settings domain contain the domain entities and components shared between service and client -->
            <groupId>io.github.jlmc</groupId>
            <artifactId>settings-domain</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <!-- Mandatory:  The applications communications depends on jackson for serialize and deserialize the network payloads, and for merging the shared entities -->
            <!-- when the application run spring-boot 4 the provided jackson version is going to be 3.x.x that have breaking changes -->
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.15.2</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <!-- Optional: Lettuce Redis Client.
            Necessary if we really want to use redis for caching the settings and reduce the latency and traffic network.
            The application using this client must provide the lettuce dependency at runtime.
            This module provides 3 RedisSettingsProvider implementations.
            1. RedisL2OnlyProvider: uses only Redis as cache layer, no cache on the client app.
            2. RedisL1L2SimpleMapProvider: uses a simple ConcurrentHashMap as L1 cache and Redis as L2 cache.
            3. RedisL1L2CaffeineProvider: uses Caffeine Cache as L1 cache and Redis as L2 cache.
            For example the spring boot application can provide it by adding the spring-boot-starter-data-redis dependency, means that this dependency will be already resolved.
            -->
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>6.6.0.RELEASE</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <!-- Optional: Caffeine Cache.
            Caffeine Cache if we really want to use Redis L1L2 with L1 Caffeine cache appropriated and recommended for production.
            This module provides 3 RedisSettingsProvider implementations.
            The Caffeine dependency must be provided when we want to use the Caffeine L1 cache, provided by the RedisL1L2CaffeineProvider.
            -->
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>3.2.3</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <!-- Optional: Nimbus JOSE + JWT
            Only necessary when we want to use  JWT tokens for authentication and authorization, provider by the PrivilegedCredentialsStrategy. Otherwise, not necessary. However, most applications will use JWT tokens, and the dependency will be already resolved.
            Necessary if we want to use JWT tokens for authentication and authorization when communicating with the Settings Service.
            The application using this client must provide the nimbus-jose-jwt dependency at runtime.
            For example the spring boot application can provide it by adding the spring-boot-starter-oauth2-resource-server dependency, means that this dependency will be already resolved.
            -->
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>10.5</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>


        <dependency>
            <!-- Optional: Resilience4jRetry module.
            Necessary if we want to use Resilience4jRetry mechanism for retrying failed requests to the Settings Service.
            This library provides a feature-flag `useRetryExecutor` (which we can define on the builder) that defined if we want to use retry mechanism or not for http request executions. If the flag is true, and we not provide your own RetryExecutor implementation, the Resilience4jRetryExecutor is going to be used, but only if the dependency is on the classpath.
            The application using this client must provide the resilience4j-retry dependency at runtime.
            For example the spring boot application can provide it by adding the resilience4j-spring-boot3 dependency, means that this dependency will be already resolved.
            -->
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-retry</artifactId>
            <version>2.2.0</version>
            <optional>true</optional>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <!-- Optional: Logging Compile-only dependencies (provided at runtime) -->
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.16</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <!-- tests dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Mockito core -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Mockito + JUnit 5 integration -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj-core.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <!--- Logging test implementation -->
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.23</version>
            <scope>test</scope>
        </dependency>

        <!-- integration tests dependencies -->
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>3.11.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>1.21.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>4.2.0</version>
            <scope>test</scope>
        </dependency>

        <!--
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>3.0.3</version>
            <scope>test</scope>
        </dependency>
        -->
    </dependencies>

    <build>
        <plugins>
            <!-- Unit tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.2</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                </configuration>
            </plugin>
            <!-- Integration tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.5.2</version>
                <executions>
                    <!-- Integration tests -->
                    <execution>
                        <id>integration-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>**/*IT.java</include>
                            </includes>
                        </configuration>
                    </execution>

                    <!-- E2E tests -->
                    <execution>
                        <id>e2e-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>**/*E2ETest.java</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>add-integration-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/integration-test/java</source>
                                <source>src/e2e-test/java</source>
                            </sources>
                            <resources>
                                <resource>
                                    <directory>src/integration-test/resources</directory>
                                </resource>
                                <resource>
                                    <directory>src/e2e-test/resources</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
